from typing import Dict

from rl_data_utils.item.serie.constants import *

# noinspection SpellCheckingInspection
CONTAINS: Final[Dict[str, str]] = {
    ACCELERATOR_SERIES: "Accelerator[_\\- ]?(Series)?",
    ACCOLADE_SERIES_1: "Accolade[_\\- ]?(1|I)?[_\\- ]?(Series)?",
    ACCOLADE_SERIES_2: "Accolade[_\\- ]?(2|II)[_\\- ]?(Series)?",
    AURIGA_SERIES: "Auriga[_\\- ]?(Series)?",
    BEACH_BLAST_SERIES: "Beach[_\\- ]?Blast[_\\- ]?(Series)?",
    BONUS_GIFT: "Bonus[_\\- ]?Gift",
    CHAMPIONS_1_SERIES: "Champions[_\\- ]?1[_\\- ]?(Series)?",
    CHAMPIONS_2_SERIES: "Champions[_\\- ]?2[_\\- ]?(Series)?",
    CHAMPIONS_3_SERIES: "Champions[_\\- ]?3[_\\- ]?(Series)?",
    CHAMPIONS_4_SERIES: "Champions[_\\- ]?4[_\\- ]?(Series)?",
    ELEVATION_SERIES: "Elevation[_\\- ]?(Series)?",
    FEROCITY_SERIES: "Ferocity[_\\- ]?(Series)?",
    GOLDEN_EGG_2020: "Golden[_\\- ]?Egg[_\\- ]?[']?(20)?20",
    GOLDEN_EGG_2019: "Golden[_\\- ]?Egg[_\\- ]?[']?(20)?19",
    GOLDEN_EGG_2018: "Golden[_\\- ]?Egg[_\\- ]?[']?(20)?18",
    GOLDEN_GIFT_2020: "Golden[_\\- ]?Gift[_\\- ]?[']?(20)?20",
    GOLDEN_GIFT_2019: "Golden[_\\- ]?Gift[_\\- ]?[']?(20)?19",
    GOLDEN_GIFT_2018: "Golden[_\\- ]?Gift[_\\- ]?[']?(20)?18",
    GOLDEN_LANTERN_2021: "Golden[_\\- ]?Lantern[_\\- ]?[']?(20)?21",
    GOLDEN_LANTERN_2020: "Golden[_\\- ]?Lantern[_\\- ]?[']?(20)?20",
    GOLDEN_LANTERN_2019: "Golden[_\\- ]?Lantern[_\\- ]?[']?(20)?19",
    GOLDEN_PUMPKIN_2020: "Golden[_\\- ]?Pumpkin[_\\- ]?[']?(20)?20",
    GOLDEN_PUMPKIN_2019: "Golden[_\\- ]?Pumpkin[_\\- ]?[']?(20)?19",
    GOLDEN_PUMPKIN_2018: "Golden[_\\- ]?Pumpkin[_\\- ]?[']?(20)?18",
    HAUNTED_HALLOWS_SERIES: "Haunted[_\\- ]?Hallows[_\\- ]?(Series)?",
    IGNITION_SERIES: "Ignition[_\\- ]?(Series)?",
    IMPACT_SERIES: "Impact[_\\- ]?(Series)?",
    MOMENTUM_SERIES: "Momentum[_\\- ]?(Series)?",
    NITRO_SERIES: "Nitro[_\\- ]?(Series)?",
    NON_CRATE: "(?:Non[_\\- ]?Crate|Post[_\\- ]?Game)",
    OVERDRIVE_SERIES: "Overdrive[_\\- ]?(Series)?",
    PLAYERS_CHOICE_SERIES: "Player(s|'s)?[_\\- ]?Choice[_\\- ]?(Series)?",
    RLCS_REWARD: "RLCS[_\\- ]?Reward",
    SEASON_1: "Season[_\\- ]?(1|I)",
    SECRET_SANTA_SERIES: "Secret[_\\- ]?Santa[_\\- ]?(Series)?",
    SPRING_FEVER_SERIES: "Spring[_\\- ]?Fever[_\\- ]?(Series)?",
    TOTALLY_AWESOME_SERIES: "Totally[_\\- ]?Awesome[_\\- ]?(Series)?",
    TRIUMPH_SERIES: "Triumph[_\\- ]?(Series)?",
    TURBO_SERIES: "Turbo[_\\- ]?(Series)?",
    VELOCITY_SERIES: "Velocity[_\\- ]?(Series)?",
    VICTORY_SERIES: "Victory[_\\- ]?(Series)?",
    VINDICATOR_SERIES: "Vindicator[_\\- ]?(Series)?",
    ZEPHYR_SERIES: "Zephyr[_\\- ]?(Series)?",
    WWE_PROMO_CODE: "WWE[_\\- ]?Promo[_\\- ]?Code"}
