from typing import Final, List

AVIATOR: Final[str] = ...
ACROBAT: Final[str] = ...
GOALKEEPER: Final[str] = ...
GUARDIAN: Final[str] = ...
JUGGLER: Final[str] = ...
NONE: Final[str] = ...
PARAGON: Final[str] = ...
PLAYMAKER: Final[str] = ...
SCORER: Final[str] = ...
SHOW_OFF: Final[str] = ...
SNIPER: Final[str] = ...
STRIKER: Final[str] = ...
SWEEPER: Final[str] = ...
TACTICIAN: Final[str] = ...
TURTLE: Final[str] = ...
VICTOR: Final[str] = ...
CERTIFICATES: Final[List[str]] = ...
