ARCHIVED = "archived"
BLUEPRINT = "blueprint"
CERTIFIED = "certified"
COLOR = "color"
CRAFTING_COST = "crafting_cost"
NAME = "name"
PAINTABLE = "paintable"
PLATFORM = "platform"
PRICE = "price"
QUANTITY = "quantity"
RARITY = "rarity"
SERIE = "serie"
SLOT = "slot"
TRADABLE = "tradable"
FAVORITE = "favorite"
FULL = [
    ARCHIVED, BLUEPRINT, CERTIFIED, COLOR, CRAFTING_COST, NAME, PAINTABLE, PLATFORM, PRICE, QUANTITY, RARITY, SERIE,
    SLOT, TRADABLE, FAVORITE]
INDENTIFIER = [NAME, RARITY, SLOT, BLUEPRINT, PLATFORM]
