from typing import Literal, List, Final

ARCHIVED: Final[str] = ...
BLUEPRINT: Final[str] = ...
CERTIFIED: Final[str] = ...
COLOR: Final[str] = ...
CRAFTING_COST: Final[str] = ...
NAME: Final[str] = ...
PAINTABLE: Final[str] = ...
PLATFORM: Final[str] = ...
PRICE: Final[str] = ...
QUANTITY: Final[str] = ...
RARITY: Final[str] = ...
SERIE: Final[str] = ...
SLOT: Final[str] = ...
TRADABLE: Final[str] = ...
FAVORITE: Final[str] = ...
AttributeName = Literal[
    'archived', 'blueprint', 'certified', 'color', 'crafting_cost', 'name', 'paintable', 'platform', 'price',
    'quantity', 'rarity', 'serie', 'slot', 'tradable', 'favorite']
FULL: List[str] = ...
INDENTIFIER: List[AttributeName] = ...
