from rl_data_utils.item.attribute.constants import AVIATOR, ACROBAT, GOALKEEPER, GUARDIAN, JUGGLER, NONE, PARAGON, \
    PLAYMAKER, SCORER, SHOW_OFF, SNIPER, STRIKER, SWEEPER, TACTICIAN, TURTLE, VICTOR, BLACK, BURNT_SIENNA, COBALT, \
    CRIMSON, DEFAULT, FOREST_GREEN, GREY, LIME, ORANGE, PINK, PURPLE, SAFFRON, SKY_BLUE, TITANIUM_WHITE, PC, PS4, \
    SWITCH, XBOX, BLACK_MARKET, COMMON, EXOTIC, IMPORT, LIMITED, PREMIUM, RARE, UNCOMMON, VERY_RARE, LEGACY, \
    ACCELERATOR, ACCOLADE_1, ACCOLADE_2, AURIGA, BEACH_BLAST, BONUS_GIFT, \
    CHAMPIONS_1, CHAMPIONS_2, CHAMPIONS_3, CHAMPIONS_4, ELEVATION, FEROCITY, \
    GOLDEN_EGG_2018, GOLDEN_EGG_2019, GOLDEN_EGG_2020, GOLDEN_GIFT_2018, GOLDEN_GIFT_2019, GOLDEN_GIFT_2020, \
    GOLDEN_LANTERN_2019, GOLDEN_LANTERN_2020, GOLDEN_LANTERN_2021, GOLDEN_PUMPKIN_2018, GOLDEN_PUMPKIN_2019, \
    GOLDEN_PUMPKIN_2020, HAUNTED_HALLOWS, IGNITION, IMPACT, MOMENTUM, NITRO, \
    NON_CRATE, OVERDRIVE, PLAYERS_CHOICE, RLCS_REWARD, SEASON_1, SECRET_SANTA, SPRING_FEVER, \
    TOTALLY_AWESOME, TRIUMPH, TURBO, VELOCITY, VICTORY, VINDICATOR, \
    ZEPHYR, WWE_PROMO_CODE, ANTENNA, BORDER, CAR, DECAL, ENGINE_AUDIO, GOAL_EXPLOSION, PAINT_FINISH, ANTHEM, \
    BANNER, BOOST, TOPPER, TRAIL, WHEEL

CERTIFICATES = (AVIATOR, ACROBAT, GOALKEEPER, GUARDIAN, JUGGLER, NONE, PARAGON, PLAYMAKER, SCORER, PLAYMAKER, SCORER,
                SHOW_OFF, SNIPER, STRIKER, SWEEPER, TACTICIAN, TURTLE, VICTOR)
COLORS = (BLACK, BURNT_SIENNA, COBALT, CRIMSON, DEFAULT, FOREST_GREEN, GREY, LIME, ORANGE, PINK,
          PURPLE, SAFFRON, SKY_BLUE, TITANIUM_WHITE)
PLATFORMS = (PC, PS4, SWITCH, XBOX)
RARITIES = (BLACK_MARKET, COMMON, EXOTIC, IMPORT, LIMITED, PREMIUM, RARE, UNCOMMON, VERY_RARE, LEGACY)
SERIES = (
    ACCELERATOR, ACCOLADE_1, ACCOLADE_2, AURIGA, BEACH_BLAST, BONUS_GIFT,
    CHAMPIONS_1, CHAMPIONS_2, CHAMPIONS_3, CHAMPIONS_4, ELEVATION, FEROCITY,
    GOLDEN_EGG_2018, GOLDEN_EGG_2019, GOLDEN_EGG_2020, GOLDEN_GIFT_2018, GOLDEN_GIFT_2019, GOLDEN_GIFT_2020,
    GOLDEN_LANTERN_2019, GOLDEN_LANTERN_2020, GOLDEN_LANTERN_2021, GOLDEN_PUMPKIN_2018, GOLDEN_PUMPKIN_2019,
    GOLDEN_PUMPKIN_2020, HAUNTED_HALLOWS, IGNITION, IMPACT, MOMENTUM, NITRO,
    NON_CRATE, OVERDRIVE, PLAYERS_CHOICE, RLCS_REWARD, SEASON_1, SECRET_SANTA, SPRING_FEVER,
    TOTALLY_AWESOME, TRIUMPH, TURBO, VELOCITY, VICTORY, VINDICATOR,
    ZEPHYR, WWE_PROMO_CODE)
SLOTS = (ANTENNA, BORDER, CAR, DECAL, ENGINE_AUDIO, GOAL_EXPLOSION, PAINT_FINISH, ANTHEM, BANNER,
         BOOST, TOPPER, TRAIL, WHEEL)
