from rl_data_utils.item.attribute.constants import AVIATOR, ACROBAT, GOALKEEPER, GUARDIAN, JUGGLER, NONE, PARAGON, \
    PLAYMAKER, SCORER, SHOW_OFF, SNIPER, STRIKER, SWEEPER, TACTICIAN, TURTLE, VICTOR, BLACK, BURNT_SIENNA, COBALT, \
    CRIMSON, DEFAULT, FOREST_GREEN, GREY, LIME, ORANGE, PINK, PURPLE, SAFFRON, SKY_BLUE, TITANIUM_WHITE, PC, PS4, \
    SWITCH, XBOX, BLACK_MARKET, COMMON, EXOTIC, IMPORT, LIMITED, PREMIUM, RARE, UNCOMMON, VERY_RARE, LEGACY, \
    ACCELERATOR, ACCOLADE_1, ACCOLADE_2, AURIGA, BEACH_BLAST, BONUS_GIFT, \
    CHAMPIONS_1, CHAMPIONS_2, CHAMPIONS_3, CHAMPIONS_4, ELEVATION, FEROCITY, \
    GOLDEN_EGG_2018, GOLDEN_EGG_2019, GOLDEN_EGG_2020, GOLDEN_GIFT_2018, GOLDEN_GIFT_2019, GOLDEN_GIFT_2020, \
    GOLDEN_LANTERN_2019, GOLDEN_LANTERN_2020, GOLDEN_LANTERN_2021, GOLDEN_PUMPKIN_2018, GOLDEN_PUMPKIN_2019, \
    GOLDEN_PUMPKIN_2020, HAUNTED_HALLOWS, IGNITION, IMPACT, MOMENTUM, NITRO, \
    NON_CRATE, OVERDRIVE, PLAYERS_CHOICE, RLCS_REWARD, SEASON_1, SECRET_SANTA, SPRING_FEVER, \
    TOTALLY_AWESOME, TRIUMPH, TURBO, VELOCITY, VICTORY, VINDICATOR, \
    ZEPHYR, WWE_PROMO_CODE, ANTENNA, BORDER, CAR, DECAL, ENGINE_AUDIO, GOAL_EXPLOSION, PAINT_FINISH, ANTHEM, \
    BANNER, BOOST, TOPPER, TRAIL, WHEEL

CERTIFICATES = (AVIATOR, ACROBAT, GOALKEEPER, GUARDIAN, JUGGLER, NONE, PARAGON, PLAYMAKER, SCORER, PLAYMAKER, SCORER,
                SHOW_OFF, SNIPER, STRIKER, SWEEPER, TACTICIAN, TURTLE, VICTOR)
COLORS = (BLACK, BURNT_SIENNA, COBALT, CRIMSON, DEFAULT, FOREST_GREEN, GREY, LIME, ORANGE, PINK,
          PURPLE, SAFFRON, SKY_BLUE, TITANIUM_WHITE)
CARS_NAMES_WITH_DECAL = ('Breakout Type-S', 'Imperator DT5', 'Peregrine TT', 'Takumi RX-T', 'X-Devil Mk2', 'Aftershock',
                         'Dominus GT', 'Octane ZSR', 'Animus GP', 'Harbinger', 'Jäger 619', 'Breakout', 'Marauder',
                         'Masamune', 'Maverick', 'Road Hog', 'Sentinel', 'Diestro', 'Dominus', 'Hotshot', 'Insidio',
                         'Paladin', 'Twinzer', 'X-Devil', 'Centio', 'Fennec', 'Komodo', 'Mantis', 'Mudcat', 'Octane',
                         'Ripper', 'Takumi', 'Triton', 'Tygris', 'Dingo', 'Esper', 'Gizmo', 'Venom', 'Endo', 'Merc')
NAMES = (
    "Bundle",
    "Credit",
    "Blueprint",
    "Golden Lantern 2021",
    "Golden Egg 2020",
    "Golden Lantern 2020",
    "Golden Pumpkin 2019",
    "Golden Egg 2019",
    "Golden Gift",
    "Golden Pumpkin 2018",
    "Golden Egg 2018",
    "Furry",
    "Cookie Dough",
    "Moon Rock",
    "Pearlescent",
    "Pearlescent (Matte)",
    "Knitted Yarn",
    "Circuit Board",
    "Burlap",
    "Glossy Block",
    "Metallic (Smooth)",
    "Metallic Pearl",
    "Metallic Pearl (Smooth)",
    "Anodized",
    "Zebra",
    "Metallic Flake",
    "Dino",
    "Straight-Line",
    "Anodized Pearl",
    "Stiletto",
    "Brushed Metal",
    "Camo",
    "Carbon Fiber",
    "Sun-Damaged",
    "Toon Sketch",
    "Toon Glossy",
    "Toon Matte",
    "Toon Wood",
    "Wood",
    "Fiberboard",
    "Chipboard",
    "Polygrid",
    "Octane",
    "Octane ZSR",
    "Road Hog",
    "Road Hog XL",
    "X-Devil",
    "X-Devil MK2",
    "Breakout",
    "Breakout Type-S",
    "Dominus",
    "Dominus GT",
    "Takumi RX-T",
    "Takumi",
    "Merc",
    "Venom",
    "Mantis",
    "Endo",
    "Centio",
    "Animus GP",
    "Jager 619",
    "Imperator DT5",
    "Werewolf",
    "Samurai",
    "Twinzer",
    "Cyclone",
    "Maverick",
    "Maverick G1",
    "Maverick GXT",
    "Nimbus",
    "Artemis GXT",
    "Diestro",
    "Guardian GXT",
    "Fennec",
    "Mudcat GXT",
    "Sentinel",
    "Chikara GXT",
    "Komodo",
    "Ronin GXT",
    "Peregrine TT",
    "Harbinger GXT",
    "Aftershock",
    "Esper",
    "Grog",
    "Marauder",
    "Masamune",
    "Proteus",
    "Ripper",
    "Scarab",
    "Triton",
    "Vulcan",
    "Zippy",
    "Insidio",
    "R3MX GXT",
    "Tygris",
    "Tyranno GXT",
    "Dingo",
    "Outlaw GXT",
    "Nexus SC",
    "Jackal",
    "Zomba",
    "Draco",
    "Voltaic",
    "Apex",
    "Alchemist",
    "Almas",
    "Dieci",
    "Falco",
    "Invader",
    "Lowrider",
    "Neptune",
    "Octavian",
    "OEM",
    "Rat Rod",
    "Spyder",
    "Stern",
    "Sunburst",
    "Trahere",
    "Tunica",
    "Veloce",
    "Vortex",
    "Asterias",
    "Gearlock",
    "Zeta",
    "Goldstone",
    "Carriage",
    "ZT-17",
    "Z-Plate",
    "Decennium",
    "Decennium Pro",
    "Ninja",
    "Sovereign Pro",
    "Mothership Pro",
    "Aero Mage Pro",
    "Hot Hot Wheels",
    "Emerald Pro",
    "WWE",
    "Chakram",
    "Chakram: Holographic",
    "Photon",
    "Looper",
    "Lobo",
    "Rhino 2",
    "Troika",
    "Discotheque",
    "Pulsus",
    "Spiralis",
    "FSL",
    "Ara-51",
    "Septem",
    "Kalos",
    "Roulette",
    "Fireplug",
    "Triplex",
    "K2",
    "SLK",
    "FGSP",
    "Turbine",
    "Chrono",
    "Clockwork",
    "Saptarishi",
    "Gaiden",
    "Revenant",
    "Grimalkin",
    "Cauldron",
    "Yuzo",
    "Hiro",
    "Equalizer",
    "Hikari P5",
    "Peppermint",
    "Christmas Wreath",
    "Wonderment",
    "Nipper",
    "Balla-Carra",
    "Infinium",
    "Aether",
    "Razzle",
    "Doughnut",
    "Lustrum X10",
    "Illuminata",
    "Diomedes",
    "Kyrios",
    "Hypnotik",
    "REEVRB",
    "Masato",
    "Reaper",
    "Centro",
    "Santa Fe",
    "Quimby",
    "Sovereign",
    "Sovereign A/T",
    "Cruxe",
    "Psyonix",
    "SARPBC-10",
    "Thread-X2",
    "Libertine",
    "Dynamo",
    "Reactor",
    "Pyramidia",
    "Capacitor I",
    "Capacitor II",
    "Capacitor III",
    "Capacitor IV",
    "Rhino",
    "Troublemaker I",
    "Troublemaker II",
    "Troublemaker III",
    "Troublemaker IV",
    "Watermelon",
    "Aero Mage",
    "Meridian",
    "Yamane",
    "Finny",
    "Gernot",
    "Raijin",
    "Demon Disc",
    "Daemon-Kelpie",
    "Gripstride HX",
    "Gripstride HX: Inverted",
    "Madness II",
    "Moko",
    "Plasmatic",
    "Polychrome",
    "Rocket Forge II",
    "Rocket Forge II: Holographic",
    "Sprocket",
    "Sprocket: Infinite",
    "Teller",
    "Holiday Hearth",
    "Jayvyn",
    "Asik",
    "Asik: Infinite",
    "Pyrrhos",
    "Pyrrhos: Inverted",
    "Zowie",
    "Zowie: Infinite",
    "Celestial II",
    "Galvan",
    "Galvan: Holographic",
    "Generator II",
    "M8",
    "MainStreet",
    "Metalwork",
    "Metalwork: Inverted",
    "Polaris",
    "Polaris: Remixed",
    "Tungsten",
    "Ulterior",
    "Ved-ava II",
    "Visionary",
    "Emerald",
    "E.T.",
    "Ghostbusters",
    "Cassette",
    "Low-Poly",
    "Sunset 1986",
    "Blender",
    "Stella",
    "Stella: Inverted",
    "P-SIMM",
    "P-SIMM: Inverted",
    "Zefram",
    "Zefram: Infinite",
    "Automaton",
    "Automaton: Inverted",
    "Camo",
    "Camo: Inverted",
    "Cephalo",
    "DRN",
    "DRN: Infinite",
    "FLT",
    "High Poly",
    "Irradiator",
    "Irradiator: Infinite",
    "Philoscope III",
    "Shutterbug",
    "Zhou GFP",
    "Clodhopper",
    "Picket",
    "Picket: Holographic",
    "Truncheon",
    "Apparatus",
    "Apparatus: Inverted",
    "Creeper",
    "NeYoYo",
    "Gyre",
    "Mendoza",
    "MetalStar",
    "Patriarch",
    "Starcourt",
    "Timbertyre",
    "Dimonix",
    "Dimonix: Inverted",
    "Helicoprion",
    "Holosphere",
    "Morrowhatch",
    "Reticle",
    "Shima",
    "Shima: Infinite",
    "Shinkei",
    "Startis",
    "Tube Tank",
    "Yankii RL",
    "Yankii RL: Infinite",
    "Yin-Yang",
    "FSL-B",
    "Spiralis R2",
    "Mistletoe",
    "Fortune",
    "Carbon",
    "Decopunk",
    "Petacio",
    "Glaive: Inverted",
    "Glaive",
    "Orbit",
    "IO: Infinite",
    "IO",
    "Tremor",
    "Tremor: Inverted",
    "Ultralex",
    "Blade Wave",
    "Blade Wave: Inverted",
    "Cyberware",
    "Jandertek",
    "Jandertek: Holographic",
    "Muscle Boy",
    "Q-Runner",
    "Shortwire",
    "Stuffed Crust",
    "Ton-Eighty",
    "TRI-2050",
    "Z-RO",
    "Z-RO: Inverted",
    "CNTCT-1",
    "CNTCT-1: Infinite",
    "Cutter",
    "Cutter: Inverted",
    "Grappler",
    "HNY",
    "HNY: Inverted",
    "Cupcake",
    "Low-Poly TE",
    "Psyonix II",
    "Sunrise 1986",
    "ANDR01D",
    "BLSSM",
    "Ferris",
    "Hamster: Holographic",
    "Hamster",
    "Hephaestus",
    "HRB-20",
    "League Shield",
    "Mandala",
    "Mandala: Infinite",
    "Propeller",
    "Propeller: Inverted",
    "SARPBC",
    "Sk8ter",
    "Stay Puft",
    "String Theory",
    "Wrathogen",
    "Aftershock",
    "Esper",
    "Grog",
    "Marauder",
    "Masamune",
    "Mothership",
    "Proteus",
    "Ripper",
    "Sanchez DC-137",
    "Scarab",
    "Spinner",
    "Triton",
    "Vulcan",
    "Zippy",
    "Cristiano",
    "Cristiano: Infinite",
    "Flim-Flam",
    "Flim-Flam: Inverted",
    "Playock",
    "Hydraul1K",
    "Shortquarter",
    "Shortquarter: Inverted",
    "Dire Wolf",
    "3-Lobe",
    "3-Lobe: Infinite",
    "Ault-SPL",
    "CDJ",
    "DYR II",
    "Esoto 4R",
    "Esoto 4R: Inverted",
    "Parabolic",
    "Polyergic",
    "Polyergic: Inverted",
    "SPN",
    "Woofer",
    "Paper-Cut",
    "Medianic",
    "Wrench-Roller",
    "Bravado",
    "Bravado: Infinite",
    "Spanner",
    "Spanner: Inverted",
    "X-Tempo",
    "X-Tempo: Radiant",
    "Imptekk",
    "Joko XL",
    "Maxle-PA",
    "Roskilde",
    "Traction: Hatch",
    "Zadeh S3",
    "Zadeh S3: Inverted",
    "Anthesis",
    "Astro-CSX",
    "Astro-CSX: Inverted",
    "Dey KC",
    "Dey KC: Schematized",
    "Glitch: Glitched",
    "Nucleon Clutch",
    "Buckboard",
    "Gadabout: Inverted",
    "Haunted Hoss",
    "Rocko",
    "Ruinator",
    "Ruinator: Inverted",
    "Tanker",
    "Tanker: Infinite",
    "Whisperer",
    "Rival",
    "Demon Disc EG",
    "Twista",
    "Twista: Revolved",
    "Enjin",
    "Enjin: Roasted",
    "Glonex: Holographic",
    "Throned",
    "Throned: Sacred",
    "Y.O.U.",
    "Canister",
    "Canister: Infinite",
    "Hasher",
    "Hasher: Revolved",
    "Jak'd",
    "Jak'd: Obverse",
    "Plasma",
    "Ion",
    "Datastream",
    "Sparkles",
    "Sacred",
    "Standard",
    "Flamethrower",
    "Thermal",
    "Gold Rush",
    "Candy Corn",
    "Xmas",
    "Toon Smoke",
    "Frostbite",
    "Hearts",
    "Lightning",
    "Lightning Yellow",
    "Polygonal",
    "Pixel Fire",
    "Trinity",
    "Dark Matter",
    "Hypernova",
    "Ink",
    "Treasure",
    "Netherworld",
    "Proton",
    "Xenosplash",
    "Tachyon",
    "Hexphase",
    "Neo Thermal",
    "Helios",
    "Magic Missile",
    "Power-Shot",
    "Cold Fusion",
    "Magmus",
    "Feather",
    "Taco",
    "Scary Pumpkin",
    "Fractal Fire",
    "Yuletide",
    "Winter Storm",
    "Toon Sketch",
    "Tsunami Beam",
    "Blast Ray",
    "Springtime Flowers",
    "Geo Soul",
    "Comet",
    "Popcorn",
    "Cirrus",
    "Enchanter",
    "Torrent",
    "Sun Ray",
    "Virtual Wave",
    "Cloudburst I",
    "Cloudburst II",
    "Cloudburst III",
    "Hot Rod",
    "Synthwave",
    "Night Terror",
    "Pickle",
    "Super Manga-Bolt III",
    "Fireworks",
    "Glitch",
    "Slash Beam III",
    "Fusion",
    "Ectoplasm",
    "Vaporwave",
    "Krackle",
    "Voltron",
    "Fiber Optic II",
    "Watermelon",
    "Ninja Star",
    "Autumn",
    "Stranger Things",
    "Cupid",
    "Radiant Gush",
    "Shining Barrage II",
    "Xmas Lights Boost",
    "Red Envelopes",
    "Flamerate",
    "Glimmerslag II",
    "HoloData",
    "Rad Rock",
    "Quasar",
    "Party Horn",
    "Vaporwave Remix",
    "Anispray",
    "League Legacy",
    "Mood Slime",
    "Supernova",
    "Toon Flame",
    "Accelerato",
    "Battle-Stars",
    "Burnout",
    "Interdimensional GB",
    "Nitrous",
    "Nuts & Bolts",
    "Rainbow",
    "Sandstorm",
    "Candyfloss",
    "HRT Beat",
    "Monsoon",
    "Bubbles",
    "Cherry Blossom",
    "Lantern Lift",
    "Ambustion",
    "Chequered Flag",
    "Diecast Spark",
    "Pylon",
    "Star Princess",
    "Xmas Lights",
    "Incantor",
    "Lava",
    "Timeline",
    "Corbital",
    "Phase-R",
    "Ethereal",
    "Alien",
    "Balloon Dog",
    "Candle",
    "Chick Magnet",
    "Cuckoo Clock",
    "Cupcake",
    "Disco Ball",
    "Doughnut",
    "Easter Egg",
    "Flower - Daisy",
    "Flower - Orchid",
    "Flower - Rose",
    "Flower - Sunflower",
    "Flower - Tulip",
    "Foam Finger",
    "Genie Lamp",
    "Giant Panda",
    "Harpoon",
    "Hot Dog",
    "Hula Girl",
    "Lollipop",
    "Macaron",
    "Parrot",
    "Pi\u00f1ata",
    "Pinwheel",
    "Rainbow Flag",
    "Rocket",
    "Rubber Duckie",
    "Satellite",
    "Seastar",
    "Trident",
    "Venus Flytrap",
    "Waffle",
    "Gold Nugget",
    "Calavera",
    "Fuzzy Skull",
    "Fuzzy Brute",
    "Fuzzy Vamp",
    "Arachnotenna",
    "Shadow Witch",
    "Candy Cane",
    "Holiday Gift",
    "Nutcracker",
    "Holiday Stocking",
    "Peppermint",
    "Dandelion Seed",
    "Koinobori",
    "WWE",
    "WWE Monday Night RAW",
    "WWE NXT",
    "WWE SmackDown Live!",
    "WWE WrestleMania 34",
    "Bubble Wand",
    "Mr. Toasty",
    "SARPBC-10",
    "Calculated",
    "Mage Glass I",
    "Mage Glass II",
    "Mage Glass III",
    "Siiick Reads",
    "Warm Watermelon",
    "Peggy Panda",
    "Dreidel",
    "Nitro Circus",
    "Fortune Fan",
    "Sparkler III",
    "Bell",
    "Big Checker",
    "Floppy Disk",
    "Naginata",
    "Celebration Kite",
    "Paper Dragon",
    "Floppy",
    "Argyled Egg",
    "Pinch Hitter",
    "RL Streamer",
    "Crescent Moon",
    "20xx",
    "Biomass",
    "Bubbly",
    "Heatwave",
    "Hexed",
    "Labyrinth",
    "Parallax",
    "Slipstream",
    "Spectre",
    "Tora",
    "Chameleon",
    "Storm Watch",
    "Trigon",
    "Dissolver",
    "Fire God",
    "Streamline",
    "Mainframe",
    "Wet Paint",
    "Hex Tide",
    "Intrudium",
    "Magma",
    "Glorifier",
    "Tidal Stream",
    "Interstellar",
    "Junk Food (Breakout)",
    "Shibuya (Breakout)",
    "Dot Matrix (Breakout)",
    "Dot Matrix (Dominus)",
    "Dot Matrix (X-Devil)",
    "Vice (Breakout)",
    "Snakeskin (Breakout)",
    "Snakeskin (Dominus)",
    "Snakeskin (Road Hog)",
    "Snakeskin (X-Devil)",
    "Snakeskin (Octane)",
    "Snakeskin (Jager 619)",
    "Snakeskin (Mantis)",
    "Falchion (Breakout)",
    "Turbo (Breakout)",
    "Distortion (Breakout)",
    "Distortion (Breakout Type-S)",
    "Distortion (Dominus GT)",
    "Distortion (Octane)",
    "Distortion (Octane ZSR)",
    "Distortion (Takumi)",
    "Distortion (Takumi RX-T)",
    "Distortion (Fennec)",
    "Funny Book (Octane ZSR)",
    "Funny Book (Breakout Type-S)",
    "Funny Book (Dominus)",
    "Royalty (Dominus)",
    "Arcana (Dominus)",
    "Pollo Caliente (Dominus)",
    "Mondo (Dominus)",
    "Unmasked (Dominus GT)",
    "MG-88 (Endo)",
    "Spatter (Endo)",
    "Mean Streak (Gizmo)",
    "Hi-Tech (Hotshot)",
    "Oni (Masamune)",
    "Narwhal (Merc)",
    "Warlock (Merc)",
    "Flower Power (Merc)",
    "Racer (Octane)",
    "Dragon Lord (Octane)",
    "MG-88 (Octane)",
    "Shisa (Octane)",
    "Kilowatt (Octane)",
    "Roadkill (Octane)",
    "Buzz Kill (Octane)",
    "Lone Wolf (Octane)",
    "Tribal (Octane ZSR)",
    "Carbonated (Road Hog)",
    "Wildfire (Road Hog)",
    "Combo (Takumi)",
    "Anubis (Takumi)",
    "Whizzle (Takumi)",
    "Super RX-T (Takumi RX-T)",
    "Flex (Venom)",
    "Nine Lives (Venom)",
    "Maximon (X-Devil)",
    "Cobra (X-Devil MK2)",
    "Suji (Dominus)",
    "Aqueous (Takumi)",
    "Sticker Bomb (Takumi)",
    "Kawaii (Masamune)",
    "Griffon (Octane)",
    "Heiwa (Breakout)",
    "Vector (Breakout)",
    "Vector (Takumi)",
    "Chainsaw (Breakout)",
    "Gigapede (Centio)",
    "RLCS (Breakout)",
    "RLCS (Breakout Type-S)",
    "RLCS (Dominus)",
    "RLCS (Dominus GT)",
    "RLCS (Octane)",
    "RLCS (Octane ZSR)",
    "RLCS X (Octane)",
    "RLCS X (Dominus)",
    "RLCS X (Fennec)",
    "Stitches (Breakout)",
    "Mobo (Breakout Type-S)",
    "MDGA (Dominus)",
    "Afterlife (Dominus)",
    "Splatter (Dominus GT)",
    "Critters (Mantis)",
    "Widow's Web (Mantis)",
    "Thanatos (Octane)",
    "Jiangshi (Octane ZSR)",
    "BOO! (Breakout)",
    "Twisted Tree",
    "Odd Fish (Animus GP)",
    "Smore'd (Breakout Type-S)",
    "Mummified (Endo)",
    "Slimline (Octane)",
    "Rad Reindeer (Breakout)",
    "Holiday Deco (Dominus)",
    "Polar Force (Endo)",
    "Cold Front (Mantis)",
    "Christmas Tree (Octane)",
    "Cold Sweater",
    "Mister Monsoon (Jager 619)",
    "Mosher (Imperator DT5)",
    "XVIII (Marauder)",
    "Athena (Merc)",
    "Ripped Comic (Octane)",
    "Froggy (Breakout)",
    "Fantasmo (Dominus)",
    "Dune Racer (Octane)",
    "Swirls",
    "Kaleidoscope",
    "Egged (Breakout)",
    "Pollinator (Centio)",
    "Callous Bros. (Dominus GT)",
    "Hip-Hop (Jager 619)",
    "Hammerhead (Mantis)",
    "Rose King (Animus GP)",
    "Machina (Centio)",
    "NNTR (Dominus GT)",
    "XVI (Jager 619)",
    "Royal Tyrant (Octane)",
    "Dot Rush (Octane)",
    "Tiger Tiger (Aftershock)",
    "Splashback (Centio)",
    "Staredown (Dominus GT)",
    "Windswept (Imperator DT5)",
    "Min-Spec (Masamune)",
    "ShapeRacer (Paladin)",
    "Sundae (Road Hog)",
    "Glyphtrix (Triton)",
    "Boo-ya!",
    "Leviathan",
    "Peacock (Animus GP)",
    "Sneaky Slither (Breakout)",
    "9 Lives (Breakout)",
    "Proptosis (Dominus)",
    "Turtle Tribe (Octane)",
    "Island King (Octane)",
    "Astaroth (Breakout)",
    "StarLighter (Jager 619)",
    "Chantico (Octane)",
    "Mechaceph (Octane ZSR)",
    "Nice Shot (Breakout)",
    "Nice Shot (Octane)",
    "What A Save! (Breakout)",
    "Savage (Dominus)",
    "Humble Pie",
    "Partly Cloudy",
    "Bobcat (Breakout)",
    "Templar (Dominus)",
    "Shark Tooth (Jager 619)",
    "Circuit Pro (Maverick)",
    "Gale-Fire (Maverick)",
    "Jetstream (Maverick)",
    "B.B. Wolf (Merc)",
    "Dr. Thrash (Octane)",
    "Space Cadet (Octane)",
    "Devil's Advocate (X-Devil)",
    "Noooo! (Octane)",
    "CRL Western (Breakout)",
    "CRL Eastern (Dominus)",
    "CRL Southern (Dominus)",
    "CRL Northern (Octane)",
    "Ripped Comic (Breakout)",
    "Sticker Bomb (Octane)",
    "Muddy (Twinzer)",
    "Retro Sun (Venom)",
    "Arachnophobia",
    "Ghost Fever (Breakout)",
    "Megabat (Mantis)",
    "Trick or Treat (Octane)",
    "Future Shock",
    "Streak Wave",
    "Alley Cat (Marauder)",
    "Watermelon (Octane)",
    "Quick Fix (Road Hog)",
    "Snowstorm",
    "Nisse (Breakout)",
    "Nitro Circus (Breakout)",
    "Winter Waddle (Dominus)",
    "Sweater Fest (Octane)",
    "Taniwha (Breakout)",
    "Gale-Fire (Octane)",
    "Windblast (Octane)",
    "Tumbling Blocks (Octane)",
    "Good Shape (Twinzer)",
    "Fireworks",
    "Mainliner",
    "Percussion",
    "Shield Glitch",
    "Easter Bunny (Breakout)",
    "Skewered (Dominus)",
    "Abducted (Octane)",
    "Quetzalcoatl (Octane)",
    "Disco Monster (X-Devil)",
    "Cobra Kai (Octane)",
    "Goop",
    "Rico (Diestro)",
    "Mixtape (Dominus)",
    "The Goonies (Octane)",
    "Vaporwave (Octane)",
    "Smooth Jazz (Twinzer)",
    "TV Time (Breakout)",
    "Ultimate Warrior (Octane)",
    "Voltron (Octane)",
    "Formation",
    "Hydro Paint",
    "Funky Medusa (Dominus)",
    "Nightmare Fuel (Dominus)",
    "Whitewash (Dominus)",
    "Conundrum (Octane)",
    "Killer Griller (Octane)",
    "Metarudia (Octane)",
    "OR-AISE (Dominus)",
    "Edge Burst (Fennec)",
    "Abtruse (Octane)",
    "Kana (Octane)",
    "RL Esports (Breakout)",
    "RL Esports (Dominus)",
    "RL Esports (Mudcat)",
    "RL Esports (Octane)",
    "Hawaiian Hopper",
    "Leafstream",
    "Spider Boogie",
    "Candy Monster (Dominus)",
    "Jacktide (Octane)",
    "Germophile",
    "Luster Edge",
    "Lycan (Breakout)",
    "Watermelon (Breakout)",
    "Zero-Sum (Breakout Type-S)",
    "Quick Fix II (Twinzer)",
    "Gift Storm",
    "Snow Devil (Breakout)",
    "Arboreal Nightmare (Dominus)",
    "Sleet Creeps (Octane)",
    "Yaojing (Breakout)",
    "Yaojing (Dominus)",
    "Dragon (Octane)",
    "Stratum Badge (Dominus)",
    "Yorebands (Fennec)",
    "Ombre (Fennec)",
    "Takeover (Komodo)",
    "Vertebrate (Octane)",
    "Bodacious (Octane)",
    "Faceted (Sentinel)",
    "Caution Waves",
    "Compound C",
    "Dune-Sweeper",
    "Huntress (Fennec)",
    "Tigress",
    "Mammoth (Breakout)",
    "Hive Mind (Gizmo)",
    "Smokescreen",
    "Z-Current",
    "Stipple Gait",
    "Auger",
    "Liquid Camo",
    "Deep Six",
    "Almagest",
    "EQ-RL",
    "Filiformer",
    "Spatiotemporal",
    "Xmas Lights Decal",
    "Dragon (Breakout)",
    "Dot Matrix (Breakout Type-S)",
    "Snakeskin (Breakout Type-S)",
    "Gentleman Beef (Dominus)",
    "Huntress (Dominus)",
    "Vector (Dominus)",
    "Dot Matrix (Dominus GT)",
    "Hardline (Fennec)",
    "Slimline (Fennec)",
    "Zeus (Fennec)",
    "Bodacious (Fennec)",
    "Wannabee (Gizmo)",
    "Mr. Coney (Insidio)",
    "Silencer (Insidio)",
    "Sticker Bomb (Insidio)",
    "Ternion (Insidio)",
    "Dragon (Merc)",
    "Watermelon (Merc)",
    "SARP Stripe (Octane)",
    "10dril (Octane)",
    "Dot Matrix (Octane ZSR)",
    "Snakeskin (Octane ZSR)",
    "Crisis (Peregrine TT)",
    "Hoodbar (Peregrine TT)",
    "Arrowhead (Takumi RX-T)",
    "Snakeskin (Takumi RX-T)",
    "Mister Rad (Tygris)",
    "Platformer (Tygris)",
    "Silencer (Tygris)",
    "Exalter",
    "W.I.P.",
    "Quickline (Harbinger)",
    "Dot Matrix (Octane)",
    "Mechwing (Peregrine tt)",
    "Framework",
    "Meteoroid",
    "Humid Haze",
    "Encryption",
    "Vaticinator",
    "Oozy",
    "Neural Network",
    "Stride Tide",
    "Starpower",
    "Vector",
    "Halo",
    "Cromulon",
    "Devil Horns",
    "Fez",
    "Fire Helmet",
    "Hard Hat",
    "Mariachi Hat",
    "Pirate's Hat",
    "Royal Crown",
    "Succulents",
    "Top Hat",
    "Witch's Hat",
    "Wizard Hat",
    "Beret",
    "Birthday Cake",
    "Bowler",
    "Brodie Helmet",
    "Bycocket",
    "Chef's Hat",
    "Derby",
    "Foam Hat",
    "Fruit Hat",
    "Hawaiian Lei",
    "Heart Glasses",
    "Homburg",
    "Ivy Cap",
    "Jack-In-The-Box",
    "Latte",
    "Little Bow",
    "Pork Pie",
    "Stegosaur",
    "Surfboard",
    "Traffic Cone",
    "Trucker Hat",
    "Unicorn",
    "Visor",
    "Antlers",
    "Baseball Cap (B)",
    "Baseball Cap (F)",
    "Biker Cap",
    "Captain's Hat",
    "Cattleman",
    "Chainsaw",
    "Cockroach",
    "Deerstalker",
    "Graduation Cap",
    "Hotcakes",
    "Light Bulb",
    "Little Bunny",
    "Little Cow",
    "Little Dog",
    "Little Elephant",
    "Little Owl",
    "Little Sloth",
    "Mouse Trap",
    "Paper Boat",
    "Party Hat",
    "Pigeon",
    "Plunger",
    "Police Hat",
    "Rasta",
    "Rhino Horns",
    "Shuriken",
    "Tiara",
    "Uncle Sam",
    "Work Boot",
    "Gold Cap",
    "Pumpkin",
    "Blitzen",
    "Robo-Visor",
    "Wildcat Ears",
    "Drink Helmet",
    "White Hat",
    "Clamshell",
    "Bone King",
    "Ghost",
    "Christmas Tree",
    "Sad Sapling",
    "Helper Elf",
    "Santa",
    "New Year's 2017",
    "Bunny Ears",
    "Easter Basket",
    "Hustle Brows",
    "Mount Champion",
    "Mrs. Avocado",
    "Mr. Banana",
    "Mr. Hot Dog",
    "Mr. Hot Pepper",
    "Worried Watermelon",
    "Sad Strawberry",
    "Catfish",
    "Octopus",
    "Butterfly",
    "Chafed Cherry",
    "Dragon Wings",
    "Fishbowl",
    "MMS Headphones",
    "Rooster Comb",
    "Gargoyle",
    "Scarecrow Jack",
    "Undying Love",
    "Grave Robber",
    "Angel Wings",
    "Fallen Tree",
    "Happy Penguin",
    "Holiday Bow",
    "Snowboards",
    "Stoic Muffin",
    "Two-Timer",
    "Dizzy Birds",
    "GG the Clown",
    "Goldfish",
    "Buzzer",
    "Kayak",
    "Mr. Pineapple",
    "Sand Castle",
    "Battle-Cars Anniversary",
    "Birthday Bash",
    "Campaign Hat",
    "Cutlass",
    "Great White",
    "Jolt Bangle I",
    "Jolt Bangle II",
    "Jolt Bangle III",
    "Phoenix Wings I",
    "Phoenix Wings II",
    "Phoenix Wings III",
    "Drip Drop",
    "LFT",
    "Candy Jack",
    "Haunted House",
    "Alarm Clock",
    "Camera",
    "Drone III",
    "Juice Box",
    "Mad Bomber",
    "Snail",
    "Udder",
    "Christmas Cocoa",
    "Sleigh-Bailed",
    "Battle Axe",
    "Hammerhead",
    "Periscope",
    "Shamrock",
    "Snare Drum",
    "Turtle Shell",
    "UFO II",
    "Hoverboard",
    "Marty Jr.",
    "Miyagi-Do",
    "Sloth's Hat",
    "Brick Phone",
    "Mixtape",
    "Phat Hat",
    "Pizza Pixel",
    "VCR",
    "Macho Man",
    "Voltron",
    "Flower - Lotus",
    "S'more",
    "Starfish",
    "Sea Turtle",
    "Silent Panda",
    "Camp Know Where",
    "Leaf Litter",
    "Qilin Horns II",
    "Crabby",
    "Flat Cap",
    "Kitten Cup",
    "Tea Kettle",
    "Tee Time",
    "Gingerbread House",
    "Happy New Year",
    "Lantern Fest",
    "Paper Dragon",
    "Richie Rat",
    "Alpinist",
    "Checkmate",
    "Sure Shot",
    "Tranquil Tangerine",
    "Pastel Eggs",
    "Double Dribble",
    "Phat Hat LIVE",
    "Pizza Pixel 2P",
    "Aquadome Buoy",
    "Cactus Cutie",
    "Ghost Trap",
    "OGBP",
    "Slimer",
    "Stay Puft",
    "Mohawk",
    "Shark Fin",
    "Accordion",
    "Keyboard",
    "X-Boards",
    "X-Skis",
    "Lucky Cat",
    "Ox Horn",
    "Ozzy Ox",
    "Jester",
    "Salty Peanut",
    "Pixelated Shades",
    "Prickly Cactus",
    "Gamepiece",
    "Happy Whale",
    "Lightspeed",
    "Blazer",
    "Friction",
    "Hot Rocks",
    "Lightning",
    "Hallowtide",
    "Zigzag",
    "Candy Cane",
    "Luminous",
    "EQ",
    "Rainbow",
    "EKG-OMG",
    "Toon Hydro",
    "Binary",
    "Laser Wave I",
    "Laser Wave II",
    "Laser Wave III",
    "Discotheque",
    "Tachyon III",
    "Winter Storm",
    "Hack Swerve III",
    "Xmas Lights Trail",
    "Ruckus",
    "Hex Fade",
    "HoloData",
    "Rad Rock",
    "Excavator",
    "SARPBC",
    "Truth Beam",
    "Toon Sketch",
    "Pixel Pointer",
    "Rumble Strip",
    "Incantor",
    "Flame Chain",
    "Tarnation",
    "Twisty-Sweet",
    "Corbital",
    "Fissure",
    "Warp Wave",
    "Ethereal",
    "Electroshock",
    "Fireworks",
    "Sub-Zero",
    "Hellfire",
    "Popcorn",
    "Party Time",
    "Reaper",
    "Vampire Bat",
    "Dueling Dragons",
    "Poly Pop",
    "Happy Holidays",
    "Toon",
    "Ballistic",
    "Butterflies",
    "Atomizer",
    "Juiced",
    "Beach Party",
    "Singularity",
    "Supernova I",
    "Supernova II",
    "Supernova III",
    "Solar Flare",
    "Quasar III",
    "Force Razor II",
    "Shattered",
    "Voxel",
    "Dust Cloud",
    "Wall Breaker II",
    "Neuro-Agitator",
    "Big Splash",
    "Floppy Fish",
    "Kablooey",
    "Meta-Blast",
    "Meteor Storm",
    "HoloData",
    "Overgrowth",
    "Rad Rock",
    "Gravity Bomb",
    "Mister Monsoon",
    "Spatial Rift",
    "Buffy-Sugo",
    "Light Show",
    "Riser",
    "Air Strike",
    "Chequered Flag",
    "Inamorata",
    "Yeehaw",
    "Carbonator",
    "Night-Mare",
    "Cosmosis",
    "Phoenix Cannon",
    "Ball King",
    "Soccer Ball",
    "Salty",
    "Dead Serious",
    "MDGA",
    "Shattered",
    "Tagged",
    "Nice Slice",
    "Rockat",
    "Starbase ARC",
    "Moai",
    "Calculated",
    "Call Sign RL",
    "Beaten Egg",
    "Dendritic",
    "Turtle",
    "Hearts",
    "Narwhal",
    "Maximon",
    "Sticker Bomb",
    "Pigeon",
    "Unicorn",
    "Junk Food",
    "Howler",
    "Zombie",
    "Cold Sweater",
    "Holiday Gifts",
    "Winter's Warmth",
    "RL Esports",
    "Winning Streak",
    "Shooting Star",
    "Soccer Splash",
    "Doughnut Eater",
    "Lift-Off",
    "WWE",
    "WWE Monday Night RAW",
    "WWE NXT",
    "WWE SmackDown Live!",
    "WWE WrestleMania 34",
    "Burnout",
    "Migraine",
    "Ice Pop",
    "S'mored",
    "Circuit Board",
    "Battle-Cars Anniversary",
    "Birthday Bash",
    "Mrs. Avocado",
    "Blueprint",
    "Camo",
    "Hoagie",
    "Rocket Labs",
    "Shark Attack",
    "Soccar Nebula",
    "Sushi Roll",
    "Trash It!",
    "Vice",
    "Solar System",
    "Triplicate",
    "Lucky Stars",
    "Bob's Ramen",
    "Ghost Story",
    "Gamer Pad",
    "Gold-Plated",
    "Tread Heavily",
    "Frostline",
    "Hat Trick",
    "Aloha",
    "Blueprint II",
    "Sticker Shock",
    "Fighter Junk",
    "Retro Fresh",
    "BKR",
    "NeOctane",
    "Sunset 1986",
    "Knight Rider",
    "Vaporwave",
    "Avant-Garde",
    "Checkered Flag",
    "Venom Ride",
    "Ouchie",
    "Copper Crisis",
    "Neon Runner",
    "Demogorgon",
    "Scoops Ahoy",
    "Hibiscus",
    "Kaze",
    "Tranquility",
    "Valorous",
    "Xmas Lights Banner",
    "Goodbye Nian",
    "Fallen Angel",
    "Statesman",
    "Pixel Fire",
    "Hornet",
    "Metropolis",
    "RNSM",
    "Hypnoteks",
    "Picnic",
    "Tranquil Toff",
    "Frosted Cake",
    "Wet Wash",
    "Ecto-1",
    "Ghostbusters",
    "RLCS X",
    "Pulse Crawler",
    "Faboo",
    "Knuckle Huck",
    "Temple Guardian",
    "Sweet Dreams",
    "Chequered Flag I",
    "HNY",
    "Hot Ice",
    "Spectral",
    "Free Ride",
    "Twinkle Box",
    "Fire Main",
    "Crown",
    "Damaged",
    "SDTV",
    "Paladin",
    "Scoops Ahoy",
    "Happy Holidays",
    "Snowman",
    "Spring Pagoda",
    "Tranquility",
    "Frosted Cake",
    "Jolted",
    "Ghostbusters",
    "Joker",
    "Dolphino",
    "Go-Kart",
    "Motormouth",
    "Muscle Car",
    "Electro-Mag",
    "Initializer",
    "Bootlegger",
    "Heinrich"
)
PLATFORMS = (PC, PS4, SWITCH, XBOX)
RARITIES = (BLACK_MARKET, COMMON, EXOTIC, IMPORT, LIMITED, PREMIUM, RARE, UNCOMMON, VERY_RARE, LEGACY)
SERIES = (
    ACCELERATOR, ACCOLADE_1, ACCOLADE_2, AURIGA, BEACH_BLAST, BONUS_GIFT,
    CHAMPIONS_1, CHAMPIONS_2, CHAMPIONS_3, CHAMPIONS_4, ELEVATION, FEROCITY,
    GOLDEN_EGG_2018, GOLDEN_EGG_2019, GOLDEN_EGG_2020, GOLDEN_GIFT_2018, GOLDEN_GIFT_2019, GOLDEN_GIFT_2020,
    GOLDEN_LANTERN_2019, GOLDEN_LANTERN_2020, GOLDEN_LANTERN_2021, GOLDEN_PUMPKIN_2018, GOLDEN_PUMPKIN_2019,
    GOLDEN_PUMPKIN_2020, HAUNTED_HALLOWS, IGNITION, IMPACT, MOMENTUM, NITRO,
    NON_CRATE, OVERDRIVE, PLAYERS_CHOICE, RLCS_REWARD, SEASON_1, SECRET_SANTA, SPRING_FEVER,
    TOTALLY_AWESOME, TRIUMPH, TURBO, VELOCITY, VICTORY, VINDICATOR,
    ZEPHYR, WWE_PROMO_CODE)
SLOTS = (ANTENNA, BORDER, CAR, DECAL, ENGINE_AUDIO, GOAL_EXPLOSION, PAINT_FINISH, ANTHEM, BANNER,
         BOOST, TOPPER, TRAIL, WHEEL)
KINDS = ['Infinite', 'Inverted', 'Holographic']
