from __future__ import annotations

from rl_data_utils.item.attribute.preset import AVIATOR, ACROBAT, GOALKEEPER, GUARDIAN, JUGGLER, NONE, PARAGON, \
    PLAYMAKER, SCORER, SHOW_OFF, SNIPER, STRIKER, SWEEPER, TACTICIAN, TURTLE, VICTOR, BLACK, BURNT_SIENNA, COBALT, \
    CRIMSON, DEFAULT, FOREST_GREEN, GREY, LIME, ORANGE, PINK, PURPLE, SAFFRON, SKY_BLUE, TITANIUM_WHITE, PC, PS4, \
    SWITCH, XBOX, BLACK_MARKET, COMMON, EXOTIC, IMPORT, LIMITED, PREMIUM, RARE, UNCOMMON, VERY_RARE, LEGACY, \
    ACCELERATOR_SERIES, ACCOLADE_SERIES_1, ACCOLADE_SERIES_2, AURIGA_SERIES, BEACH_BLAST_SERIES, BONUS_GIFT, \
    CHAMPIONS_1_SERIES, CHAMPIONS_2_SERIES, CHAMPIONS_3_SERIES, CHAMPIONS_4_SERIES, ELEVATION_SERIES, FEROCITY_SERIES, \
    GOLDEN_EGG_2018, GOLDEN_EGG_2019, GOLDEN_EGG_2020, GOLDEN_GIFT_2018, GOLDEN_GIFT_2019, GOLDEN_GIFT_2020, \
    GOLDEN_LANTERN_2019, GOLDEN_LANTERN_2020, GOLDEN_LANTERN_2021, GOLDEN_PUMPKIN_2018, GOLDEN_PUMPKIN_2019, \
    GOLDEN_PUMPKIN_2020, HAUNTED_HALLOWS_SERIES, IGNITION_SERIES, IMPACT_SERIES, MOMENTUM_SERIES, NITRO_SERIES, \
    NON_CRATE, OVERDRIVE_SERIES, PLAYERS_CHOICE_SERIES, RLCS_REWARD, SEASON_1, SECRET_SANTA_SERIES, SPRING_FEVER_SERIES, \
    TOTALLY_AWESOME_SERIES, TRIUMPH_SERIES, TURBO_SERIES, VELOCITY_SERIES, VICTORY_SERIES, VINDICATOR_SERIES, \
    ZEPHYR_SERIES, WWE_PROMO_CODE, ANTENNA, BORDER, CAR, DECAL, ENGINE_AUDIO, GOAL_EXPLOSION, PAINT_FINISH, ANTHEM, \
    BANNER, BOOST, TOPPER, TRAIL, WHEEL
from rl_data_utils.item.attribute_data.attribute_data import Certificates, Colors, Platforms, Rarities, Series, Slots

CERTIFICATES = Certificates(
    (AVIATOR, ACROBAT, GOALKEEPER, GUARDIAN, JUGGLER, NONE, PARAGON, PLAYMAKER, SCORER, SHOW_OFF,
     SNIPER, STRIKER, SWEEPER, TACTICIAN, TURTLE, VICTOR))
COLORS = Colors((BLACK, BURNT_SIENNA, COBALT, CRIMSON, DEFAULT, FOREST_GREEN, GREY, LIME, ORANGE, PINK,
                 PURPLE, SAFFRON, SKY_BLUE, TITANIUM_WHITE))
PLATFORMS = Platforms((PC, PS4, SWITCH, XBOX))
RARITIES = Rarities((BLACK_MARKET, COMMON, EXOTIC, IMPORT, LIMITED, PREMIUM, RARE, UNCOMMON, VERY_RARE, LEGACY))
SERIES = Series(
    (ACCELERATOR_SERIES, ACCOLADE_SERIES_1, ACCOLADE_SERIES_2, AURIGA_SERIES, BEACH_BLAST_SERIES, BONUS_GIFT,
     CHAMPIONS_1_SERIES, CHAMPIONS_2_SERIES, CHAMPIONS_3_SERIES, CHAMPIONS_4_SERIES, ELEVATION_SERIES, FEROCITY_SERIES,
     GOLDEN_EGG_2018, GOLDEN_EGG_2019, GOLDEN_EGG_2020, GOLDEN_GIFT_2018, GOLDEN_GIFT_2019, GOLDEN_GIFT_2020,
     GOLDEN_LANTERN_2019, GOLDEN_LANTERN_2020, GOLDEN_LANTERN_2021, GOLDEN_PUMPKIN_2018, GOLDEN_PUMPKIN_2019,
     GOLDEN_PUMPKIN_2020, HAUNTED_HALLOWS_SERIES, IGNITION_SERIES, IMPACT_SERIES, MOMENTUM_SERIES, NITRO_SERIES,
     NON_CRATE, OVERDRIVE_SERIES, PLAYERS_CHOICE_SERIES, RLCS_REWARD, SEASON_1, SECRET_SANTA_SERIES,
     SPRING_FEVER_SERIES,
     TOTALLY_AWESOME_SERIES, TRIUMPH_SERIES, TURBO_SERIES, VELOCITY_SERIES, VICTORY_SERIES, VINDICATOR_SERIES,
     ZEPHYR_SERIES, WWE_PROMO_CODE))
SLOTS = Slots((ANTENNA, BORDER, CAR, DECAL, ENGINE_AUDIO, GOAL_EXPLOSION, PAINT_FINISH, ANTHEM, BANNER,
               BOOST, TOPPER, TRAIL, WHEEL))
