IS_ACCELERATOR_SERIES = r'^Accelerator[_\- ]?(Series)?$'
IS_BEACH_BLAST_SERIES = r'^Beach[_\- ]?Blast[_\- ]?(Series)?$'
IS_BONUS_GIFT = r'^Bonus[_\- ]?Gift$'
IS_CHAMPIONS_1_SERIES = r'^Champions[_\- ]?1[_\- ]?(Series)?$'
IS_CHAMPIONS_2_SERIES = r'^Champions[_\- ]?2[_\- ]?(Series)?$'
IS_CHAMPIONS_3_SERIES = r'^Champions[_\- ]?3[_\- ]?(Series)?$'
IS_CHAMPIONS_4_SERIES = r'^Champions[_\- ]?4[_\- ]?(Series)?$'
IS_ELEVATION_SERIES = r'^Elevation[_\- ]?(Series)?$'
IS_FEROCITY_SERIES = r'^Ferocity[_\- ]?(Series)?$'
IS_GOLDEN_EGG_2020 = r'^Golden[_\- ]?Egg[_\- ]?["\']?(20)?20$'
IS_GOLDEN_EGG_2019 = r'^Golden[_\- ]?Egg[_\- ]?["\']?(20)?19$'
IS_GOLDEN_EGG_2018 = r'^Golden[_\- ]?Egg[_\- ]?["\']?(20)?18$'
IS_GOLDEN_GIFT_2020 = r'^Golden[_\- ]?Gift[_\- ]?["\']?(20)?20$'
IS_GOLDEN_GIFT_2019 = r'^Golden[_\- ]?Gift[_\- ]?["\']?(20)?19$'
IS_GOLDEN_GIFT_2018 = r'^Golden[_\- ]?Gift[_\- ]?["\']?(20)?18$'
IS_GOLDEN_LANTERN_2021 = r'^Golden[_\- ]?Lantern[_\- ]?["\']?(20)?21$'
IS_GOLDEN_LANTERN_2020 = r'^Golden[_\- ]?Lantern[_\- ]?["\']?(20)?20$'
IS_GOLDEN_PUMPKIN_2020 = r'^Golden[_\- ]?Pumpkin[_\- ]?["\']?(20)?20$'
IS_GOLDEN_PUMPKIN_2019 = r'^Golden[_\- ]?Pumpkin[_\- ]?["\']?(20)?19$'
IS_GOLDEN_PUMPKIN_2018 = r'^Golden[_\- ]?Pumpkin[_\- ]?["\']?(20)?18$'
IS_HAUNTED_HALLOWS_SERIES = r'^Haunted[_\- ]?Hallows[_\- ]?(Series)?$'
IS_IMPACT_SERIES = r'^Impact[_\- ]?(Series)?$'
IS_NITRO_SERIES = r'^Nitro[_\- ]?(Series)?$'
IS_NON_CRATE = r'^Non[_\- ]?Crate|Post[_\- ]?Game$'
IS_OVERDRIVE_SERIES = r'^Overdrive[_\- ]?(Series)?$'
IS_PLAYERS_CHOICE_SERIES = r'^Player\'s[_\- ]?Choice[_\- ]?(Series)?$'
IS_SECRET_SANTA_SERIES = r'^Secret[_\- ]?Santa[_\- ]?(Series)?$'
IS_SPRING_FEVER_SERIES = r'^Spring[_\- ]?Fever[_\- ]?(Series)?$'
IS_TOTALLY_AWESOME_SERIES = r'^Totally[_\- ]?Awesome[_\- ]?(Series)?$'
IS_TRIUMPH_SERIES = r'^Triumph[_\- ]?(Series)?$'
IS_TURBO_SERIES = r'^Turbo[_\- ]?(Series)?$'
IS_VELOCITY_SERIES = r'^Velocity[_\- ]?(Series)?$'
IS_VICTORY_SERIES = r'^Victory[_\- ]?(Series)?$'
IS_VINDICATOR_SERIES = r'^Vindicator[_\- ]?(Series)?$'
IS_ZEPHYR_SERIES = r'^Zephyr[_\- ]?(Series)?$'
CONTAINS_ACCELERATOR_SERIES = r'Accelerator[_\- ]?(Series)?'
CONTAINS_BEACH_BLAST_SERIES = r'Beach[_\- ]?Blast[_\- ]?(Series)?'
CONTAINS_BONUS_GIFT = r'Bonus[_\- ]?Gift'
CONTAINS_CHAMPIONS_1_SERIES = r'Champions[_\- ]?1[_\- ]?(Series)?'
CONTAINS_CHAMPIONS_2_SERIES = r'Champions[_\- ]?2[_\- ]?(Series)?'
CONTAINS_CHAMPIONS_3_SERIES = r'Champions[_\- ]?3[_\- ]?(Series)?'
CONTAINS_CHAMPIONS_4_SERIES = r'Champions[_\- ]?4[_\- ]?(Series)?'
CONTAINS_ELEVATION_SERIES = r'Elevation[_\- ]?(Series)?'
CONTAINS_FEROCITY_SERIES = r'Ferocity[_\- ]?(Series)?'
CONTAINS_GOLDEN_EGG_2020 = r'Golden[_\- ]?Egg[_\- ]?["\']?(20)?20'
CONTAINS_GOLDEN_EGG_2019 = r'Golden[_\- ]?Egg[_\- ]?["\']?(20)?19'
CONTAINS_GOLDEN_EGG_2018 = r'Golden[_\- ]?Egg[_\- ]?["\']?(20)?18'
CONTAINS_GOLDEN_GIFT_2020 = r'Golden[_\- ]?Gift[_\- ]?["\']?(20)?20'
CONTAINS_GOLDEN_GIFT_2019 = r'Golden[_\- ]?Gift[_\- ]?["\']?(20)?19'
CONTAINS_GOLDEN_GIFT_2018 = r'Golden[_\- ]?Gift[_\- ]?["\']?(20)?18'
CONTAINS_GOLDEN_LANTERN_2021 = r'Golden[_\- ]?Lantern[_\- ]?["\']?(20)?21'
CONTAINS_GOLDEN_LANTERN_2020 = r'Golden[_\- ]?Lantern[_\- ]?["\']?(20)?20'
CONTAINS_GOLDEN_PUMPKIN_2020 = r'Golden[_\- ]?Pumpkin[_\- ]?["\']?(20)?20'
CONTAINS_GOLDEN_PUMPKIN_2019 = r'Golden[_\- ]?Pumpkin[_\- ]?["\']?(20)?19'
CONTAINS_GOLDEN_PUMPKIN_2018 = r'Golden[_\- ]?Pumpkin[_\- ]?["\']?(20)?18'
CONTAINS_HAUNTED_HALLOWS_SERIES = r'Haunted[_\- ]?Hallows[_\- ]?(Series)?'
CONTAINS_IMPACT_SERIES = r'Impact[_\- ]?(Series)?'
CONTAINS_NITRO_SERIES = r'Nitro[_\- ]?(Series)?'
CONTAINS_NON_CRATE = r'(?:Non[_\- ]?Crate|Post[_\- ]?Game)'
CONTAINS_OVERDRIVE_SERIES = r'Overdrive[_\- ]?(Series)?'
CONTAINS_PLAYERS_CHOICE_SERIES = r'Player\'s[_\- ]?Choice[_\- ]?(Series)?'
CONTAINS_SECRET_SANTA_SERIES = r'Secret[_\- ]?Santa[_\- ]?(Series)?'
CONTAINS_SPRING_FEVER_SERIES = r'Spring[_\- ]?Fever[_\- ]?(Series)?'
CONTAINS_TOTALLY_AWESOME_SERIES = r'Totally[_\- ]?Awesome[_\- ]?(Series)?'
CONTAINS_TRIUMPH_SERIES = r'Triumph[_\- ]?(Series)?'
CONTAINS_TURBO_SERIES = r'Turbo[_\- ]?(Series)?'
CONTAINS_VELOCITY_SERIES = r'Velocity[_\- ]?(Series)?'
CONTAINS_VICTORY_SERIES = r'Victory[_\- ]?(Series)?'
CONTAINS_VINDICATOR_SERIES = r'Vindicator[_\- ]?(Series)?'
CONTAINS_ZEPHYR_SERIES = r'Zephyr[_\- ]?(Series)?'
CONTAINS_REGEXS = [CONTAINS_ACCELERATOR_SERIES, CONTAINS_BEACH_BLAST_SERIES, CONTAINS_BONUS_GIFT,
                   CONTAINS_CHAMPIONS_1_SERIES, CONTAINS_CHAMPIONS_2_SERIES, CONTAINS_CHAMPIONS_3_SERIES,
                   CONTAINS_CHAMPIONS_4_SERIES, CONTAINS_ELEVATION_SERIES, CONTAINS_FEROCITY_SERIES,
                   CONTAINS_GOLDEN_EGG_2018, CONTAINS_GOLDEN_EGG_2019, CONTAINS_GOLDEN_EGG_2020,
                   CONTAINS_GOLDEN_GIFT_2018, CONTAINS_GOLDEN_GIFT_2019, CONTAINS_GOLDEN_GIFT_2020,
                   CONTAINS_GOLDEN_LANTERN_2020, CONTAINS_GOLDEN_LANTERN_2021,
                   CONTAINS_GOLDEN_PUMPKIN_2018, CONTAINS_GOLDEN_PUMPKIN_2019, CONTAINS_GOLDEN_PUMPKIN_2020,
                   CONTAINS_HAUNTED_HALLOWS_SERIES, CONTAINS_IMPACT_SERIES, CONTAINS_NITRO_SERIES, CONTAINS_NON_CRATE,
                   CONTAINS_OVERDRIVE_SERIES, CONTAINS_PLAYERS_CHOICE_SERIES, CONTAINS_SECRET_SANTA_SERIES,
                   CONTAINS_SPRING_FEVER_SERIES, CONTAINS_TOTALLY_AWESOME_SERIES, CONTAINS_TRIUMPH_SERIES,
                   CONTAINS_TURBO_SERIES, CONTAINS_VELOCITY_SERIES, CONTAINS_VICTORY_SERIES,
                   CONTAINS_VINDICATOR_SERIES, CONTAINS_ZEPHYR_SERIES]
