from typing import Final, List

BLACK_MARKET: Final[str] = ...
COMMON: Final[str] = ...
EXOTIC: Final[str] = ...
IMPORT: Final[str] = ...
LEGACY: Final[str] = ...
LIMITED: Final[str] = ...
PREMIUM: Final[str] = ...
RARE: Final[str] = ...
UNCOMMON: Final[str] = ...
VERY_RARE: Final[str] = ...
RARITIES: Final[List[str]] = ...
