from typing import Final, List

BLACK: Final[str] = ...
BURNT_SIENNA: Final[str] = ...
COBALT: Final[str] = ...
CRIMSON: Final[str] = ...
DEFAULT: Final[str] = ...
FOREST_GREEN: Final[str] = ...
GREY: Final[str] = ...
LIME: Final[str] = ...
ORANGE: Final[str] = ...
PINK: Final[str] = ...
PURPLE: Final[str] = ...
SAFFRON: Final[str] = ...
SKY_BLUE: Final[str] = ...
TITANIUM_WHITE: Final[str] = ...
COLORS: Final[List[str]] = ...
