from typing import Final, List

ANTENNA: Final[str] = ...
BORDER: Final[str] = ...
CAR: Final[str] = ...
BLUEPRINT: Final[str] = ...
DECAL: Final[str] = ...
ENGINE_AUDIO: Final[str] = ...
GOAL_EXPLOSION: Final[str] = ...
GIFT_PACK: Final[str] = ...
PAINT_FINISH: Final[str] = ...
ANTHEM: Final[str] = ...
BANNER: Final[str] = ...
BOOST: Final[str] = ...
TOPPER: Final[str] = ...
TRAIL: Final[str] = ...
WHEEL: Final[str] = ...
TITLE: Final[str] = ...
SLOTS: Final[List[str]] = ...