AVIATOR = "Aviator"
ACROBAT = "Acrobat"
GOALKEEPER = "Goalkeeper"
GUARDIAN = "Guardian"
JUGGLER = "Juggler"
NONE = "None"
PARAGON = "Paragon"
PLAYMAKER = "Playmaker"
SCORER = "Scorer"
SHOW_OFF = "Show-off"
SNIPER = "Sniper"
STRIKER = "Striker"
SWEEPER = "Sweeper"
TACTICIAN = "Tactician"
TURTLE = "Turtle"
VICTOR = "Victor"
BLACK = "Black"
BURNT_SIENNA = "Burnt Sienna"
COBALT = "Cobalt"
CRIMSON = "Crimson"
DEFAULT = "Default"
FOREST_GREEN = "Forest Green"
GREY = "Grey"
LIME = "Lime"
ORANGE = "Orange"
PINK = "Pink"
PURPLE = "Purple"
SAFFRON = "Saffron"
SKY_BLUE = "Sky Blue"
TITANIUM_WHITE = "Titanium White"
CREDITS = 'Credits'
PC = 'Pc'
PS4 = 'Ps4'
SWITCH = 'Switch'
XBOX = 'Xbox'
BLACK_MARKET = "Black market"
COMMON = "Common"
EXOTIC = "Exotic"
IMPORT = "Import"
LEGACY = "Legacy"
LIMITED = "Limited"
PREMIUM = "Premium"
RARE = "Rare"
UNCOMMON = "Uncommon"
VERY_RARE = "Very rare"
ACCELERATOR_SERIES = 'Accelerator Series'
ACCOLADE_SERIES_1 = 'Accolade 1 Series'
ACCOLADE_SERIES_2 = 'Accolade 2 Series'
AURIGA_SERIES = 'Auriga Series'
BEACH_BLAST_SERIES = 'Beach Blast Series'
BONUS_GIFT = 'Bonus Gift'
CHAMPIONS_1_SERIES = 'Champions 1 Series'
CHAMPIONS_2_SERIES = 'Champions 2 Series'
CHAMPIONS_3_SERIES = 'Champions 3 Series'
CHAMPIONS_4_SERIES = 'Champions 4 Series'
ELEVATION_SERIES = 'Elevation Series'
FEROCITY_SERIES = 'Ferocity Series'
GOLDEN_EGG_2020 = 'Golden Egg 2020'
GOLDEN_EGG_2019 = 'Golden Egg 2019'
GOLDEN_EGG_2018 = 'Golden Egg 2018'
GOLDEN_GIFT_2020 = 'Golden Gift 2020'
GOLDEN_GIFT_2019 = 'Golden Gift 2019'
GOLDEN_GIFT_2018 = 'Golden Gift 2018'
GOLDEN_LANTERN_2021 = 'Golden Lantern 2021'
GOLDEN_LANTERN_2020 = 'Golden Lantern 2020'
GOLDEN_LANTERN_2019 = 'Golden Lantern 2019'
GOLDEN_PUMPKIN_2020 = 'Golden Pumpkin 2020'
GOLDEN_PUMPKIN_2019 = 'Golden Pumpkin 2019'
GOLDEN_PUMPKIN_2018 = 'Golden Pumpkin 2018'
HAUNTED_HALLOWS_SERIES = 'Haunted Hallows Series'
IGNITION_SERIES = 'Ignition Series'
IMPACT_SERIES = 'Impact Series'
MOMENTUM_SERIES = 'Momentum Series'
NITRO_SERIES = 'Nitro Series'
NON_CRATE = 'Non Crate'
OVERDRIVE_SERIES = 'Overdrive Series'
PLAYERS_CHOICE_SERIES = 'Player\'s Choice Series'
RLCS_REWARD = 'RLCS Reward'
SEASON_1 = 'Season 1'
SECRET_SANTA_SERIES = 'Secret Santa Series'
SPRING_FEVER_SERIES = 'Spring Fever Series'
TOTALLY_AWESOME_SERIES = 'Totally Awesome Series'
TRIUMPH_SERIES = 'Triumph Series'
TURBO_SERIES = 'Turbo Series'
VELOCITY_SERIES = 'Velocity Series'
VICTORY_SERIES = 'Victory Series'
VINDICATOR_SERIES = 'Vindicator Series'
ZEPHYR_SERIES = 'Zephyr Series'
WWE_PROMO_CODE = 'WWE Promo Code'
ANTENNA = "Antenna"
BORDER = "Avatar Border"
CAR = "Car"
BLUEPRINT = 'Blueprint'
DECAL = "Decal"
ENGINE_AUDIO = "Engine Audio"
GOAL_EXPLOSION = "Goal Explosion"
GIFT_PACK = "Gift Pack"
PAINT_FINISH = "Paint Finish"
ANTHEM = "Anthem"
BANNER = "Banner"
BOOST = "Boost"
TOPPER = "Topper"
TRAIL = "Trail"
WHEEL = "Wheel"
TITLE = 'Title'
