from __future__ import annotations

from rl_data_utils.item.attribute import constants
from rl_data_utils.item.attribute.attribute import Certified, Color, Platform, Slot, Rarity, Serie, Favorite, Blueprint, \
    Archived, Tradable, Name

# Names
CREDITS = Name(constants.CREDITS)
# Certificates
AVIATOR = Certified(constants.AVIATOR)
ACROBAT = Certified(constants.ACROBAT)
GOALKEEPER = Certified(constants.GOALKEEPER)
GUARDIAN = Certified(constants.GUARDIAN)
JUGGLER = Certified(constants.JUGGLER)
NONE = Certified(constants.NONE)
PARAGON = Certified(constants.PARAGON)
PLAYMAKER = Certified(constants.PLAYMAKER)
SCORER = Certified(constants.SCORER)
SHOW_OFF = Certified(constants.SHOW_OFF)
SNIPER = Certified(constants.SNIPER)
STRIKER = Certified(constants.STRIKER)
SWEEPER = Certified(constants.SWEEPER)
TACTICIAN = Certified(constants.TACTICIAN)
TURTLE = Certified(constants.TURTLE)
VICTOR = Certified(constants.VICTOR)
# Colors
BLACK = Color(constants.BLACK)
BURNT_SIENNA = Color(constants.BURNT_SIENNA)
COBALT = Color(constants.COBALT)
CRIMSON = Color(constants.CRIMSON)
DEFAULT = Color(constants.DEFAULT)
FOREST_GREEN = Color(constants.FOREST_GREEN)
GREY = Color(constants.GREY)
LIME = Color(constants.LIME)
ORANGE = Color(constants.ORANGE)
PINK = Color(constants.PINK)
PURPLE = Color(constants.PURPLE)
SAFFRON = Color(constants.SAFFRON)
SKY_BLUE = Color(constants.SKY_BLUE)
TITANIUM_WHITE = Color(constants.TITANIUM_WHITE)
# Platforms
PC = Platform(constants.PC)
PS4 = Platform(constants.PS4)
SWITCH = Platform(constants.SWITCH)
XBOX = Platform(constants.XBOX)
# Rarities
BLACK_MARKET = Rarity(constants.BLACK_MARKET)
COMMON = Rarity(constants.COMMON)
EXOTIC = Rarity(constants.EXOTIC)
IMPORT = Rarity(constants.IMPORT)
LEGACY = Rarity(constants.LEGACY)
LIMITED = Rarity(constants.LIMITED)
PREMIUM = Rarity(constants.PREMIUM)
RARE = Rarity(constants.RARE)
UNCOMMON = Rarity(constants.UNCOMMON)
VERY_RARE = Rarity(constants.VERY_RARE)
# Series
ACCELERATOR_SERIES = Serie(constants.ACCELERATOR)
ACCOLADE_SERIES_1 = Serie(constants.ACCOLADE_1)
ACCOLADE_SERIES_2 = Serie(constants.ACCOLADE_2)
AURIGA_SERIES = Serie(constants.AURIGA)
BEACH_BLAST_SERIES = Serie(constants.BEACH_BLAST)
BONUS_GIFT = Serie(constants.BONUS_GIFT)
CHAMPIONS_1_SERIES = Serie(constants.CHAMPIONS_1)
CHAMPIONS_2_SERIES = Serie(constants.CHAMPIONS_2)
CHAMPIONS_3_SERIES = Serie(constants.CHAMPIONS_3)
CHAMPIONS_4_SERIES = Serie(constants.CHAMPIONS_4)
ELEVATION_SERIES = Serie(constants.ELEVATION)
FEROCITY_SERIES = Serie(constants.FEROCITY)
GOLDEN_EGG_2020 = Serie(constants.GOLDEN_EGG_2020)
GOLDEN_EGG_2019 = Serie(constants.GOLDEN_EGG_2019)
GOLDEN_EGG_2018 = Serie(constants.GOLDEN_EGG_2018)
GOLDEN_GIFT_2020 = Serie(constants.GOLDEN_GIFT_2020)
GOLDEN_GIFT_2019 = Serie(constants.GOLDEN_GIFT_2019)
GOLDEN_GIFT_2018 = Serie(constants.GOLDEN_GIFT_2018)
GOLDEN_LANTERN_2021 = Serie(constants.GOLDEN_LANTERN_2021)
GOLDEN_LANTERN_2020 = Serie(constants.GOLDEN_LANTERN_2020)
GOLDEN_LANTERN_2019 = Serie(constants.GOLDEN_LANTERN_2019)
GOLDEN_PUMPKIN_2020 = Serie(constants.GOLDEN_PUMPKIN_2020)
GOLDEN_PUMPKIN_2019 = Serie(constants.GOLDEN_PUMPKIN_2019)
GOLDEN_PUMPKIN_2018 = Serie(constants.GOLDEN_PUMPKIN_2018)
HAUNTED_HALLOWS_SERIES = Serie(constants.HAUNTED_HALLOWS)
IGNITION_SERIES = Serie(constants.IGNITION)
IMPACT_SERIES = Serie(constants.IMPACT)
MOMENTUM_SERIES = Serie(constants.MOMENTUM)
NITRO_SERIES = Serie(constants.NITRO)
NON_CRATE = Serie(constants.NON_CRATE)
OVERDRIVE_SERIES = Serie(constants.OVERDRIVE)
PLAYERS_CHOICE_SERIES = Serie(constants.PLAYERS_CHOICE)
RLCS_REWARD = Serie(constants.RLCS_REWARD)
SEASON_1 = Serie(constants.SEASON_1)
SECRET_SANTA_SERIES = Serie(constants.SECRET_SANTA)
SPRING_FEVER_SERIES = Serie(constants.SPRING_FEVER)
TOTALLY_AWESOME_SERIES = Serie(constants.TOTALLY_AWESOME)
TRIUMPH_SERIES = Serie(constants.TRIUMPH)
TURBO_SERIES = Serie(constants.TURBO)
VELOCITY_SERIES = Serie(constants.VELOCITY)
VICTORY_SERIES = Serie(constants.VICTORY)
VINDICATOR_SERIES = Serie(constants.VINDICATOR)
ZEPHYR_SERIES = Serie(constants.ZEPHYR)
WWE_PROMO_CODE = Serie(constants.WWE_PROMO_CODE)
# Slots
ANTENNA = Slot(constants.ANTENNA)
BORDER = Slot(constants.BORDER)
CAR = Slot(constants.CAR)
BLUEPRINTS = Slot(constants.BLUEPRINTS)
DECAL = Slot(constants.DECAL)
ENGINE_AUDIO = Slot(constants.ENGINE_AUDIO)
GOAL_EXPLOSION = Slot(constants.GOAL_EXPLOSION)
GIFT_PACK = Slot(constants.GIFT_PACK)
PAINT_FINISH = Slot(constants.PAINT_FINISH)
ANTHEM = Slot(constants.ANTHEM)
BANNER = Slot(constants.BANNER)
BOOST = Slot(constants.BOOST)
TOPPER = Slot(constants.TOPPER)
TRAIL = Slot(constants.TRAIL)
WHEEL = Slot(constants.WHEEL)
TITLE = Slot(constants.TITLE)
# Favorite
FAVORITE = Favorite(True)
NOT_FAVORITE = Favorite(False)
# Blueprint
BLUEPRINT = Blueprint(True)
NOT_BLUEPRINT = Blueprint(True)
# Archived
ARCHIVED = Archived(True)
NOT_ARCHIVED = Archived(False)
# Tradable
TRADABLE = Tradable(True)
NOT_TRADABLE = Tradable(False)
